/**
 * Barrel (index.ts) 模板渲染器
 */
import type { MethodInfo } from "../core";

/**
 * 渲染 Barrel 导出模板
 */
export function renderBarrelTemplate(
  methods: MethodInfo[],
  type: "mutation" | "query"
): string {
  const suffix = type === "mutation" ? "Mutation" : "Query";
  const fileExt = type === "mutation" ? ".mutation" : ".query";

  const lines: string[] = [
    "/**",
    ` * ${suffix} 导出入口`,
    " *",
    " * @generated by repository-implementation-generator",
    " */",
    "",
  ];

  for (const method of methods) {
    const className = generateClassName(method.methodName, suffix);
    lines.push(
      `export { ${className} } from "./${method.operationName}${fileExt}";`
    );
  }

  lines.push("");

  return lines.join("\n");
}

/**
 * 生成类名
 */
function generateClassName(methodName: string, suffix: string): string {
  const capitalizedMethod =
    methodName.charAt(0).toUpperCase() + methodName.slice(1);
  return `${capitalizedMethod}${suffix}`;
}
