/**
 * Mapper 模板渲染器
 */
import type { GeneratorContext } from "../core";

/**
 * 渲染 Mapper 模板
 */
export function renderMapperTemplate(context: GeneratorContext): string {
  const { aggregateName, aggregateCamel, domainRelativePath } = context;

  const lines: string[] = [
    "/**",
    ` * ${aggregateName} Mapper`,
    " *",
    " * 聚合根 ⇄ 持久化模型 转换",
    " *",
    " * @generated by repository-implementation-generator",
    " * @keep-reason TODO: 完善映射逻辑后移除 .keep 后缀",
    " */",
    "",
    `// TODO: 导入 Drizzle Schema 类型`,
    `// import type { New${aggregateName}, ${aggregateName} as ${aggregateName}Row } from "@/infrastructure/database/schema/...";`,
    "",
    `import { ${aggregateName}Aggregate } from "${domainRelativePath}";`,
    "",
    "/**",
    ` * 持久化数据类型（根据实际表结构调整）`,
    " */",
    `export interface ${aggregateName}PersistenceData {`,
    `  // TODO: 定义持久化数据结构`,
    `  ${aggregateCamel}: unknown;`,
    "}",
    "",
    "/**",
    ` * ${aggregateName} Mapper`,
    " */",
    `export class ${aggregateName}Mapper {`,
    "  /**",
    "   * 持久化模型 → 聚合根",
    "   */",
    `  static toDomain(data: ${aggregateName}PersistenceData): ${aggregateName}Aggregate {`,
    "    // TODO: 实现持久化模型到领域模型的转换",
    `    throw new Error("Not implemented: ${aggregateName}Mapper.toDomain");`,
    "  }",
    "",
    "  /**",
    "   * 聚合根 → 持久化模型（创建）",
    "   */",
    `  static toPersistence(aggregate: ${aggregateName}Aggregate): unknown {`,
    "    // TODO: 实现领域模型到持久化模型的转换",
    `    throw new Error("Not implemented: ${aggregateName}Mapper.toPersistence");`,
    "  }",
    "",
    "  /**",
    "   * 聚合根 → 更新数据",
    "   */",
    `  static toUpdateData(aggregate: ${aggregateName}Aggregate): unknown {`,
    "    // TODO: 实现更新数据的提取",
    `    throw new Error("Not implemented: ${aggregateName}Mapper.toUpdateData");`,
    "  }",
    "}",
    "",
  ];

  return lines.join("\n");
}
