/**
 * Mutation 模板渲染器
 */
import type { GeneratorContext, MethodInfo } from "../core";

/**
 * 渲染 Mutation 模板
 */
export function renderMutationTemplate(
  method: MethodInfo,
  context: GeneratorContext
): string {
  const { aggregateName, aggregateCamel, domainRelativePath } = context;
  const className = generateClassName(method.methodName, aggregateName, "Mutation");

  // Mutation 文件在 mutations/ 子目录，需要额外加一层 ../
  const adjustedDomainPath = "../" + domainRelativePath;

  // 构建参数列表
  const paramsStr = method.parameters
    .map((p) => `${p.name}${p.isOptional ? "?" : ""}: ${p.type}`)
    .join(", ");

  // 构建参数导入类型
  const paramTypes = method.parameters
    .map((p) => extractBaseType(p.type))
    .filter((t) => !isPrimitiveType(t));

  const lines: string[] = [
    "/**",
    ` * ${method.description || method.methodName}`,
    " *",
    " * @generated by repository-implementation-generator",
    " * @keep-reason TODO: 完善业务逻辑后移除 .keep 后缀",
    " */",
    "",
    `import { DATABASE_SERVICE, DatabaseService } from "@/infrastructure/database";`,
    `// TODO: 导入正确的 Drizzle Schema 表`,
    `// import { ${aggregateCamel}s } from "@/infrastructure/database/schema/...";`,
  ];

  // 添加 drizzle-orm 导入
  lines.push(`import { eq } from "drizzle-orm";`);
  lines.push(`import { inject, injectable } from "tsyringe";`);
  lines.push("");

  // 添加领域类型导入（使用调整后的路径）
  if (paramTypes.length > 0) {
    lines.push(`import type { ${paramTypes.join(", ")} } from "${adjustedDomainPath}";`);
  }
  lines.push("");

  // 类定义
  lines.push("/**");
  lines.push(` * ${method.description || method.methodName} Mutation`);
  lines.push(" */");
  lines.push("@injectable()");
  lines.push(`export class ${className} {`);
  lines.push("  constructor(");
  lines.push("    @inject(DATABASE_SERVICE) private readonly dbService: DatabaseService,");
  lines.push("  ) {}");
  lines.push("");
  lines.push("  /**");
  lines.push("   * 执行变更操作");
  lines.push("   */");
  lines.push(`  async execute(${paramsStr}): ${method.returnType} {`);
  lines.push("    // TODO: 实现变更逻辑");
  lines.push(`    throw new Error("Not implemented: ${className}.execute");`);
  lines.push("  }");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

/**
 * 生成类名
 */
function generateClassName(
  methodName: string,
  aggregateName: string,
  suffix: string
): string {
  // save -> Save{Aggregate}{Suffix}
  // delete -> Delete{Aggregate}{Suffix}
  const capitalizedMethod =
    methodName.charAt(0).toUpperCase() + methodName.slice(1);
  return `${capitalizedMethod}${suffix}`;
}

/**
 * 提取基础类型名
 */
function extractBaseType(typeStr: string): string {
  // Promise<UserAggregate> -> UserAggregate
  // UserAggregate | null -> UserAggregate
  // Array<User> -> User
  return typeStr
    .replace(/Promise<(.+)>/g, "$1")
    .replace(/\s*\|\s*null/g, "")
    .replace(/\s*\|\s*undefined/g, "")
    .replace(/Array<(.+)>/g, "$1")
    .replace(/\[\]/g, "")
    .trim();
}

/**
 * 是否为原始类型
 */
function isPrimitiveType(type: string): boolean {
  const primitives = [
    "string",
    "number",
    "boolean",
    "void",
    "null",
    "undefined",
    "any",
    "unknown",
    "never",
  ];
  return primitives.includes(type.toLowerCase());
}
